---
title: "中間発表スライド準備"
output: html_document
---

# Setting{.tabset .tabset-fade .tabset-pills}

- option, package, database setting

## knitr option

```{r set up, message=FALSE}
# set directory
setwd("~/Desktop/Datacomp2018/") 
# max.print 
options(max.print="20", digits=5)
# Global options
library(knitr)
opts_chunk$set(echo=TRUE,
               cache = FALSE,
	             prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.width = 11)
opts_knit$set(width=75)
```

## other

```{r package, message=FALSE}
library(tidyverse)
library(summarytools) # summary easily for EDA
library(skimr) 
library(RPostgreSQL)
library(dbplyr)
library(lubridate)
library(ggthemes)
library(ggpmisc)
library(ggforce)
library(scales)
library(doParallel)
library(foreach)
library(DT)
library(gridExtra)
# set ggplot theme
theme_set(theme_classic(base_size = 18,base_family = "Helvetica"))
# function
source('~/Desktop/DataComp2018/script/function.R')
# sql set
source('~/Desktop/DataComp2018/script/sql_connect.R')
```

# Report 

- 中間発表に向けて, アイデアや目標などを示す.

## url

- [GRPの計算方法について](http://www.sales-ntv.com/jissen/pattern.html)
- [広告費用について](https://tech.nikkeibp.co.jp/it/article/Keyword/20080409/298530/)
- 
## 目標

- 広告効果モデル

従来手法のGRP(延べ視聴率)

## 基礎集計用

### TVに関する諸情報

```{r}
p1 <- program %>% 
  left_join(sta,by="station_code") %>% 
  select(station_jp) %>% 
  group_by(station_jp) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  dplyr::collect() %>% 
  ggplot(aes(x= factor(station_jp),y = count)) +
    theme_set(theme_classic(base_size = 18,base_family = "HiraKakuPro-W3")) +
    geom_bar(stat = "identity",fill = "steelblue") +
    coord_flip() +
    theme(axis.title.x = element_blank()) +
    labs(x="チャンネル") 

p2 <- program %>% 
  left_join(br_format,by="br_format") %>% 
  select(br_format_naiyou) %>% 
  group_by(br_format_naiyou) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  dplyr::collect() %>% 
  ggplot(aes(x= factor(br_format_naiyou),y = count)) +
    theme_set(theme_classic(base_size = 18,base_family = "HiraKakuPro-W3")) +
    geom_bar(stat = "identity",fill = "steelblue") +
    coord_flip() +
    theme(axis.title.x = element_blank()) +
    labs(x="放送形式") 

p3 <- program %>% 
  left_join(ban1,by="ban_code1") %>% 
  select(ban_code1_naiyou) %>% 
  group_by(ban_code1_naiyou) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  dplyr::collect() %>% 
  ggplot(aes(x= factor(ban_code1_naiyou),y = count)) +
    theme_set(theme_classic(base_size = 18,base_family = "HiraKakuPro-W3")) +
    geom_bar(stat = "identity",fill = "steelblue") +
    coord_flip() +
    theme(axis.title.x = element_blank()) +
    labs(x="番組大分類") 
p <- gridExtra::grid.arrange(p1,p2,p3,nrow=3)
```

```{r eval=FALSE}
ggsave(file = "~/Desktop/DataComp2018/image/basic/番組情報の基礎集計(チャンネルと番組特性と大分類).png", plot = p, dpi = 100, width = 10, height = 9.3)
```

### CM時点データ

```{r}
p1 <- cm %>% 
  left_join(adv, "adv_type") %>% 
  group_by(adv_type_name) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  dplyr::collect() %>% 
  ggplot(aes(x= factor(adv_type_name),y = count)) +
    theme_set(theme_classic(base_size = 18,base_family = "HiraKakuPro-W3")) +
    geom_bar(stat = "identity",fill = "steelblue") +
    coord_flip() +
    theme(axis.title.x = element_blank()) +
    labs(x="広告種類") 
```

```{r eval=FALSE}
ggsave(file = "~/Desktop/DataComp2018/image/basic/CMの基礎集計(広告種類).png", plot = p1, dpi = 100, width = 10, height = 9.3)
```