---
title: "House number について"
author: "kotsubo takuto"
output: 
    html_document:
      md_extensions: -ascii_identifiers
      toc: true
      toc_depth: 3
      code_folding: hide
---

# Setting{.tabset .tabset-fade .tabset-pills}

## knitr option

```{r reset, include=FALSE}
# 初期化
rm(list = ls())
```

```{r set up, message=FALSE}
# set directory
setwd("~/Desktop/DataComp2018/") 
# max.print 
options(max.print="200", digits=5)
# Global options
library(knitr)
opts_chunk$set(echo=TRUE,
               cache = FALSE,
	             prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## Library package

```{r package, message=FALSE}
library(tidyverse)
library(RPostgreSQL)
```

## Test code

```{r}
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv,dbname="video",host="133.31.57.120",port=4508,user="m1",password="shi0hama")
ataset <- dbGetQuery(con,"SELECT * FROM original.job_mst")
ataset
```

